### selene関連情報定義 ###
selene:
  webdriver:
    chrome: C:/pleiades/workspace_aucper/RuoYi-Vue/ruoyi-aucper/webdrivers/chromedriver.exe
    gecko: C:/pleiades/workspace_aucper/RuoYi-Vue/ruoyi-aucper/webdrivers/geckodriver.exe
  pool:
    max-size: 5
    min-idle: 5
  grid-json:
    hub: C:/pleiades/workspace_aucper/RuoYi-Vue/ruoyi-aucper/src/main/resources/hubConfig.json
    node: C:/pleiades/workspace_aucper/RuoYi-Vue/ruoyi-aucper/src/main/resources/nodeConfig.json